name: fauth
description: A Flutter 2FA-App to generate Time-Based One-Time Passwords.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  otp: ^1.0.3
  qrcode_reader: ^0.4.4
  objectdb: ^1.0.5
  path_provider: ^0.5.0+1
  material_design_icons_flutter: ^3.1.3493
  dynamic_theme: ^1.0.1
  clipboard_manager: ^0.0.4
  flutter_i18n: ^0.6.3
  flare_flutter: 1.3.6 # Render issue with 1.3.7
  flare_dart: 1.3.4
  flutter_slidable: ^0.4.9
  intro_slider: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.0"
  
flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/icon/icon.png"
  image_path_ios: "assets/icon/icon_ios.png"
  adaptive_icon_background: "#3F51B5"
  adaptive_icon_foreground: "assets/icon/adaptive_icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/i18n/
    - assets/flare/
    - assets/images/
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
